SELECT jns_konstruksi,input_ajl.no_mesin,
AVG(CASE DAY(tgl_input) WHEN 1 THEN eff ELSE NULL END ) AS '1',
(CASE DAY(tgl_input) WHEN 2 THEN eff ELSE '' END ) AS '2',
(CASE DAY(tgl_input) WHEN 3 THEN eff ELSE '' END ) AS '3',
(CASE DAY(tgl_input) WHEN 4 THEN eff ELSE '' END ) AS '4',
(CASE DAY(tgl_input) WHEN 5 THEN eff ELSE '' END ) AS '5',
(CASE DAY(tgl_input) WHEN 6 THEN eff ELSE '' END ) AS '6',
(CASE DAY(tgl_input) WHEN 7 THEN eff ELSE '' END ) AS '7',
(CASE DAY(tgl_input) WHEN 8 THEN eff ELSE '' END ) AS '8',
(CASE DAY(tgl_input) WHEN 9 THEN eff ELSE '' END ) AS '9',
(CASE DAY(tgl_input) WHEN 10 THEN eff ELSE '' END ) AS '10',
(CASE DAY(tgl_input) WHEN 11 THEN eff ELSE '' END ) AS '11',
(CASE DAY(tgl_input) WHEN 12 THEN eff ELSE '' END ) AS '12',
(CASE DAY(tgl_input) WHEN 13 THEN eff ELSE '' END ) AS '13',
(CASE DAY(tgl_input) WHEN 14 THEN eff ELSE '' END ) AS '14',
SUM(CASE DAY(tgl_input) WHEN 15 THEN eff ELSE '' END ) AS '15',
(CASE DAY(tgl_input) WHEN 16 THEN eff ELSE '' END ) AS '16',
(CASE DAY(tgl_input) WHEN 17 THEN eff ELSE '' END ) AS '17',
(CASE DAY(tgl_input) WHEN 18 THEN eff ELSE '' END ) AS '18',
(CASE DAY(tgl_input) WHEN 19 THEN eff ELSE '' END ) AS '19',
SUM(CASE DAY(tgl_input) WHEN 20 THEN eff ELSE '' END ) AS '20',
(CASE DAY(tgl_input) WHEN 21 THEN eff ELSE '' END ) AS '21',
AVG(CASE DAY(tgl_input) WHEN 22 THEN eff ELSE '' END ) AS '22',
(CASE DAY(tgl_input) WHEN 23 THEN eff ELSE '' END ) AS '23',
(CASE DAY(tgl_input) WHEN 24 THEN eff ELSE '' END ) AS '24',
(CASE DAY(tgl_input) WHEN 25 THEN eff ELSE '' END ) AS '25',
(CASE DAY(tgl_input) WHEN 26 THEN eff ELSE '' END ) AS '26',
(CASE DAY(tgl_input) WHEN 27 THEN eff ELSE '' END ) AS '27',
(CASE DAY(tgl_input) WHEN 28 THEN eff ELSE '' END ) AS '28',
(CASE DAY(tgl_input) WHEN 29 THEN eff ELSE '' END ) AS '29',
(CASE DAY(tgl_input) WHEN 30 THEN eff ELSE '' END ) AS '30',
(CASE DAY(tgl_input) WHEN 31 THEN eff ELSE '' END ) AS '31'
FROM input_ajl, mesin
WHERE input_ajl.`no_mesin`=mesin.`no_mesin` AND MONTH(tgl_input)= 3
GROUP BY tgl_input